@node Illuminants
@chapter Illuminants

@command{libcolour} provides a number of initialisers
macros for standard illuminants. The following macros
expand to a @code{libcolour_ciexyy_t} with the standard
2 degrees observer value in CIE xyY, each have a
supplementary 10 degrees observer counterpart using
suffix @code{_10DEG_OBS}, both with the Y value set
to 1.

@table @code
@item LIBCOLOUR_ILLUMINANT_A
CIE Standard Illuminant A.@*
Incandescent/Tungsten.@*
2855.54 K (2848 K in old definition of 1 K).

@item LIBCOLOUR_ILLUMINANT_B
CIE Standard Illuminant B.@*
Direct sunlight at noon (obsolete).@*
4874 K.

@item LIBCOLOUR_ILLUMINANT_C
CIE Standard Illuminant C.@*
Average/north sky daylight (obsolete).@*
6774 K.

@item LIBCOLOUR_ILLUMINANT_D50
CIE Standard Illuminant D50.@*
Horizon Light.@*
5002.78 K (5000 K in old definition of 1 K).

@item LIBCOLOUR_ILLUMINANT_D55
CIE Standard Illuminant D55.@*
Mid-morning/mid-afternoon daylight.@*
5503.06 K (5500 K in old definition of 1 K).

@item LIBCOLOUR_ILLUMINANT_D65
CIE Standard Illuminant D65.@*
Noon daylight.@*
6503.62 K (6500 K in old definition of 1 K).

@item LIBCOLOUR_ILLUMINANT_D75
CIE Standard Illuminant D75.@*
North sky daylight.@*
7504.17 K (7500 K in old definition of 1 K).

@item LIBCOLOUR_ILLUMINANT_E
CIE Standard Illuminant E.@*
Equal energy.@*
5454 K.

@item LIBCOLOUR_ILLUMINANT_F1
CIE Standard Illuminant F1.@*
Daylight fluorescent.@*
6430 K.

@item LIBCOLOUR_ILLUMINANT_F2
CIE Standard Illuminant F2.@*
Cool white fluorescent.@*
4230 K.

@item LIBCOLOUR_ILLUMINANT_F3
CIE Standard Illuminant F3.@*
White fluorescent.@*
3450 K.

@item LIBCOLOUR_ILLUMINANT_F4
CIE Standard Illuminant F4.@*
Warm white fluorescent.@*
2940 K.

@item LIBCOLOUR_ILLUMINANT_F5
CIE Standard Illuminant F5.@*
Daylight fluorescent.@*
6350 K.

@item LIBCOLOUR_ILLUMINANT_F6
CIE Standard Illuminant F6.@*
Lite white fluorescent.@*
4150 K.

@item LIBCOLOUR_ILLUMINANT_F7
CIE Standard Illuminant F7.@*
D65 simulator, daylight simulator.@*
6500 K.

@item LIBCOLOUR_ILLUMINANT_F8
CIE Standard Illuminant F8.@*
D50 simulator, Sylvania F40 Design 50.@*
5000 K.

@item LIBCOLOUR_ILLUMINANT_F9
CIE Standard Illuminant F9.@*
Cool white deluxe fluorescent.@*
4150 K.

@item LIBCOLOUR_ILLUMINANT_F10
CIE Standard Illuminant F10.@*
Philips TL85, Ultralume 50.@*
5000 K.

@item LIBCOLOUR_ILLUMINANT_F11
CIE Standard Illuminant F11.@*
Philips TL84, Ultralume 40.@*
4000 K.

@item LIBCOLOUR_ILLUMINANT_F12
CIE Standard Illuminant F12.@*
Philips TL83, Ultralume 30.@*
3000 K.

@end table
