.TH LIBCOLOUR_SRGB_DECODE 3 libcolour
.SH NAME
libcolour_srgb_decode - Unapply the sRGB transfer function
.SH SYNOPSIS
.nf
#include <libcolour.h>

float       \fBlibcolour_srgb_decode_f\fP(float \fIvalue\fP);
double      \fBlibcolour_srgb_decode_lf\fP(double \fIvalue\fP);
long double \fBlibcolour_srgb_decode_llf\fP(long double \fIvalue\fP);

#define \fBlibcolour_srgb_decode\fP(\fIvalue\fP)\\
	(_Generic((\fIvalue\fP),\\
	          float:       \fBlibcolour_srgb_decode_f\fP(\fIvalue\fP),\\
	          double:      \fBlibcolour_srgb_decode_lf\fP(\fIvalue\fP),\\
	          long double: \fBlibcolour_srgb_decode_llf\fP(\fIvalue\fP)))
.fi
.SH DESCRIPTION
.B libcolour_srgb_decode
and its non-generic functions unapply the sRGB transfer
function to a
.IR value .
If
.I value
is negative, the transfer function is unapplied to the
absolute value of
.I value
and the negative of the result is returned.
.SH SEE ALSO
.BR libcolour (7),
.BR libcolour_srgb_encode (3),
.BR LIBCOLOUR_SRGB (7)
.SH AUTHORS
Mattias Andrée
.RI < maandree@kth.se >
