.TH LIBCOLOUR_CIEXYY 7 libcolour
.SH NAME
LIBCOLOUR_CIEXYY - CIE xyY
.SH DESCRIPTION
CIE xyY colours are presented with either of
.nf

	\fBtypedef struct libcolour_ciexyy_f libcolour_ciexyy_f_t;\fP
	\fBtypedef struct libcolour_ciexyy_lf libcolour_ciexyy_lf_t;\fP
	\fBtypedef struct libcolour_ciexyy_llf libcolour_ciexyy_llf_t;\fP

.fi
These
.BR struct s
use
.BR float ,
.BR double ,
and
.BR long\ double ,
respecitively, for the values stored in them,
and are otherwise identical.
.B struct libcolour_ciexyy_f
is defined as
.nf

	\fBstruct libcolour_ciexyy_f {\fP
		\fBenum libcolour_model\fP \fImodel\fP\fB;\fP
		\fBfloat\fP \fIx\fP\fB;\fP
		\fBfloat\fP \fIy\fP\fB;\fP
		\fBfloat\fP \fIY\fP\fB;\fP
	\fB};\fP

.fi
.I .model
shall be set to
.BR LIBCOLOUR_CIEXYY .
In
.BR union\ libcolour_colour_f ,
.BR union\ libcolour_colour_lf ,
and
.BR union\ libcolour_colour_llf ,
.I .ciexyy
is used for CIE xyY colours.
.P
.IR .x ,
.IR .y ,
and
.I .Y
hold the unscaled x, y, and Y values, respectively.
.P
CIE xyY is not additive, nor is it linearily
isomorphic to CIE 1931 XYZ. Rather, it is defined by
x = X/(X + Y + Z), y = Y/(X + Y + Z), where X, Y, and
Z are the CIE 1931 XYZ values (with the same names)
for the same colour. The value Y is the same in both
colour models.
.P
This colour model is derived from CIE 1931 XYZ and
is primarily used for representing chromaticities.
.SH SEE ALSO
.BR libcolour (7)
.SH AUTHORS
Mattias Andrée
.RI < maandree@kth.se >
