.TH LIBCOLOUR_YPBPR 7 libcolour
.SH NAME
LIBCOLOUR_YPBPR - YPbPr
.SH DESCRIPTION
YPbPr [the \(aqb\(a and the \(aqr\(aq should be in subscript and capitalised]
colours are presented with either of
.nf

	typedef struct libcolour_ypbpr_f libcolour_ypbpr_f_t;
	typedef struct libcolour_ypbpr_lf libcolour_ypbpr_lf_t;
	typedef struct libcolour_ypbpr_llf libcolour_ypbpr_llf_t;

.fi
These
.BR struct s
use
.BR float ,
.BR double ,
and
.BR long\ double ,
respecitively, for the values stored in them,
and are otherwise identical.
.B struct libcolour_ypbpr_f
is defined as
.nf

	struct libcolour_ypbpr_f {
		enum libcolour_model \fImodel\fP;
		float \fIY\fP;
		float \fIPb\fP;
		float \fIPr\fP;
	};

.fi
.I .model
shall be set to
.BR LIBCOLOUR_YPBPR .
In
.BR union\ libcolour_colour_f ,
.BR union\ libcolour_colour_lf ,
and
.BR union\ libcolour_colour_llf ,
.I .ypbpr
is used for YPbPr colours.
.P
.IR .Y ,
.IR .Pb ,
and
.I .Pr
hold the Y (luma), Pb [the \(aqb\(aq should be in
subscript and capitalised], and Pr [the \(aqr\(aq
should be in subscript and capitalised] values,
respectively.
.P
Y is 0 in black and 1 in white.
Pb is the difference between Y and blue.
Pr is the difference between Y and red.
.P
YPbPr is additive, since it is linearly isomorphic
to CIE 1931 XYZ. It's white point is the
CIE Standard Illuminant D65.
.SH SEE ALSO
.BR libcolour (7)
.SH AUTHORS
Mattias Andrée
.RI < maandree@kth.se >
